* Background
* Basic types
** Article Type
   The basic unit of the RSS feed is the article. The article consists of a
   description, URL, title, and a date. This is passed around inside of feed
   objects.
   #+BEGIN_SRC python :tangle SimpleRSS.py
     class Article:
         def __init__(self):
             self.description = ""
             self.url = ""
             self.title = ""
             self.published_date = ""

         def __str__(self):
             return "title: {}\n\tdescription: {}\n\tlink: {}\n\tpublished_date: {}".format(self.title, self.description, self.url, self.published_date)
   #+END_SRC
** Image type
   The image type is the XML object that contains the feed's favicon URL & title.
   #+BEGIN_SRC python :tangle SimpleRSS.py
     class Image:
        def __init__(self):
           self.title = ""
           self.url = ""
           self.link = ""
   #+END_SRC
** Feed type
   The feed type is the thing that will be parsed out of an XML document overall. It consists of articles, etc

   #+BEGIN_SRC python :tangle SimpleRSS.py
     class Feed:
         def __init__(self):
             self.image = Image()
             self.articles = []

             self.link = ""
             self.last_build_date = ""
             self.title = ""

         def __str__(self):
             return "{} \n\t- link:{}\n\t- last_build_date: {}\n\t- {} article(s)".format(self.title, self.link, self.last_build_date, len(self.articles))
   #+END_SRC
* Parsers
  This RSS parser is designed to be a parser for RSS feeds, but I do also intend
  to use it for some other feed types (atom, etc) in the future. To make that
  easier, I am interested in setting things up in a way that I can reuse easily,
  and I think the right way to do that for right now is to use something like a
  strategy pattern where every parser knows how to resolve some part of the
  feed. In the future, it may be worthwhile to make the parsers here strategies
  in a true strategy pattern and have the system somehow intelligently determine
  what kind of a feed we are dealing with.
** Image parser
   #+BEGIN_SRC python :tangle SimpleRSS.py
     class ArticleParser:
         def parse(self, xml_doc):
             article = Article()

             article.description = xml_doc.find("description").text
             article.title = xml_doc.find("title").text
             article.url = xml_doc.find("link").text
             article.published_date = xml_doc.find("pubDate").text

             return article
   #+END_SRC
